name: Single string with multiple output parameters

on:
  workflow_dispatch:

jobs:

  single_string_multiple_output_params:

    runs-on: ubuntu-latest

    steps:
      - name: Output multiple parameters
        id: params
        run: echo -e "bumped=1\nmessage=Bump 7.4 to 7.4.33, 8.2 to 8.2.18 and 8.3 to 8.3.6" >> $GITHUB_OUTPUT

      - name: Read params
        run: |
          echo "param1: ${{ steps.params.outputs.bumped }}"
          echo "param2: ${{ steps.params.outputs.message }}"
